### ISSUE TITLE
Problems on Godot 4.2.2.

### ISSUE THREAD

**Issue by DNAGamesGit** [FeatureKillersGames/FirebaseAnalyticsGodotAndroidPlugin#3]
Hello. how can i update a plugin? can you help pls? i update godot to 4.2.2. and export doesnt work with plugin v1.0 version. 

@BasilYes

**Comment by BasilYes** [comment]
Just build last commit, or wait some time I will do it myself

**Comment by DNAGamesGit** [comment]
Thank you for your reply. I don't know how to build from the last commit. Ok i will wait.

> Just build last commit, or wait some time I will do it myself

**Comment by BasilYes** [comment]
Done, try it. Sorry for waiting.

**Comment by timlukastlt** [comment]
Hey,
i think v101 is still not published to the assetlib as i can only see 1.0

**Comment by BasilYes** [comment]
> Hey, i think v101 is still not published to the assetlib as i can only see 1.0

Yes, it is. I little bit busy, so it's not tested for 4.2.2. If you try it, and it's will work I will update assetlib entry

**Comment by timlukastlt** [comment]
Okay im not able to download it via AssetLibary through Godot but i will build it myself and test it out :)

**Comment by BasilYes** [comment]
You can just download it from latest release

**Comment by timlukastlt** [comment]
I built it myself without any issues, and it worked perfectly in Godot 4.2.2! 🥳

You know what? You’re a genius! I’m so happy that you created this project—it’s the first one that actually worked and successfully sent data to Firebase. If you have some time, I’d love to learn more about how you created this project and possibly help maintain it, as it’s been incredibly helpful for me.

Thank you so much!

**Comment by BasilYes** [comment]
> I built it myself without any issues, and it worked perfectly in Godot 4.2.2! 🥳
> 
> You know what? You’re a genius! I’m so happy that you created this project—it’s the first one that actually worked and successfully sent data to Firebase. If you have some time, I’d love to learn more about how you created this project and possibly help maintain it, as it’s been incredibly helpful for me.
> 
> Thank you so much!

Hahahaha. Thanks for your kind words, but it's just bunch of strange hacks and tricks. You can ask whatever you want. (telegram: https://t.me/BasilYes , discord: basilyes and matrix: @basilyes:matrix.org)
